### ISSUE TITLE
Allow addon maintainers to ocabot merge migration PRs

### ISSUE THREAD

**Issue by sbidoul** [OCA/oca-github-bot#122]
First thing is to write down the algorithm...

**Comment by legalsylvain** [comment]
Hi @sbidoul : I'm very interested by this one. I don't know how to implement it however.

Use case : 
- I  developed a module named ``account_template_active`` in https://github.com/OCA/account-financial-tools (branch 12.0). [link](https://github.com/OCA/account-financial-tools/tree/12.0/account_template_active)
- Someone port this module in V14.0. (https://github.com/OCA/account-financial-tools/pull/1187)
- I'd like to merge the PR once the approval process is done.

Different approaches at the first sight : 
1. git fetch various previous branches (13.0, 12.0, 11.0, ...), until founding a branch that contain an installable module name ``account_template_active``. Check if the user that call ``ocabot merge`` is the maintainer of the latest version of the module.
2. Call github and wget ``https://github.com/OCA/account-financial-tools/blob/XX.0/account_template_active/__manifest__.py`` files and check if the manifest contains the author of the call.
3. Call via API, odoo-community.org. (not sure, it seems that somebody said me it was not possible). (BTW, it seems that the instance doesn't fetch latest modules because the module ``account_template_active`` is not available on OCA website)
4. Other ?

**Comment by pedrobaeza** [comment]
As I don't know the internals of how this is done, I can't say which one is the best approach, but it seems one the third option is not very feasible. I see the number 1 as the way to go.
