### ISSUE TITLE
Missing CLABOT comment on PR by contributor without CLA

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/oca-github-bot#204]
## Module
clabot

## Describe the bug
I expected CLABOT to post a comment about the missing CLA for the submitter of https://github.com/OCA/crm/pull/441. This is a new member on my team who has not yet submitted a CLA (I also checked the OCA database and I could not find any).

**Comment by legalsylvain** [comment]
Hi @StefanRijnhart. thanks for reporting. AFAIK, it is not a bug, but more a missing feature. 
AFAIK, oca-github-bot doesn't handle cla bot check.
you can take a look on this closed PR : https://github.com/OCA/oca-github-bot/pull/31

**Comment by StefanRijnhart** [comment]
Oh, ok. So where does the code for the clabot live currently?

**Comment by legalsylvain** [comment]
I dont know ! @sbidoul, @gurneyalex ?

**Comment by sbidoul** [comment]
> So where does the code for the clabot live currently?

Actually, the current clabot lives on the [clabot branch](https://github.com/OCA/oca-github-bot/tree/clabot) of this repo.

It looks it was broken since [this commit](https://github.com/OCA/oca-github-bot/commit/2d96f4b8b7f2f22a6f31e5fb82c06d8a7670a38d) on Apr 6, and I attempt to fix it in https://github.com/OCA/oca-github-bot/pull/205 (currently deployed on the OCA server).

Let's see if things improve.
