### ISSUE TITLE
[RFC] Add to bot instructions through comments for maintaining migration issues

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/oca-github-bot#32]
A current problem is that migration issues with the list of modules to migrate is not up to date:

* Already merged of migration PRs are not checked.
* Or even worse, they are not noted.
* New migration PRs are not in the list because they weren't in the repository in the previous version when the branches were created.

I think we can inspire in `robodoo` from Odoo for putting comments for doing certain automated tasks. A flow can be:

* A PR for a migration is proposed.
* A PSC put an instruction comment indicating the module and the version it migrates: `@oca-git-bot migration 11.0 module_x`.
* The bot checks the migration issue (through the title "Migration to version X"), and fills the line with the author and the PR number, creating it if it doesn't exist.
* When the PR is merged, then the bot marks the check.
* If the PR is closed, the bot strikes-through the part of the text.
* If a new PR for the same module appears (as superseeded), and a PSC instructs the bot with the same comment in the new PR, the text for the new one is added on the line.

**Comment by emagdalenaC2i** [comment]
That flow will force all PSC to set that comments @oca-git-bot migration 11.0 module_x
with the proper release and name of the module.
Also PSC should be notified or should check if there are new migration PRs

Instead of that workflow... We can search PR with the proper name (and force users to keep a specific formating name for their PRs): [Release] [MIG] Module_name
Like
[12.0] [MIG] hr_holidays_notify_employee_manager 
So:

- the bot search for new migration PR
- The bot checks the migration issue (through the title "Migration to version X"), and fills the line with the author and the PR number, creating it if it doesn't exist.
- When the PR is merged, then the bot marks the check.
- If the PR is closed, the bot strikes-through the part of the text.
- If a new PR for the same module appears the bot create a message in the new PR with a reference to the existing PR
- If the old PR is closed (as superseeded) the bot strikes-through the part of the text and the text for the new PR is added on the line.

**Comment by pedrobaeza** [comment]
People is not going to use the correct syntax for the title, and it would be some king of "black magic", so I prefer my approach. At the end, it takes the same time to set properly the title than to put that comment. What we don't want is that a non-PSC tricks the system for referencing incorrect things, so that's why I force that this should be done by a PSC.

**Comment by legalsylvain** [comment]
If I understand correctly, this issue is fixed by https://github.com/OCA/oca-github-bot/pull/97

so can be closed ?

**Comment by pedrobaeza** [comment]
Yes!
